const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('desktopPlayer', {
    openFiles: () => ipcRenderer.invoke('library:open-files'),
    createTracksFromPaths: filePaths => ipcRenderer.invoke('library:create-tracks-from-paths', filePaths),
    getDroppedFilePath: file => webUtils.getPathForFile(file),
    loadPlaylist: () => ipcRenderer.invoke('library:load-playlist'),
    savePlaylist: data => ipcRenderer.invoke('library:save-playlist', data),
    selectRecordingOutputFolder: () => ipcRenderer.invoke('recording:select-output-folder'),
    recordTrack: (track, options) => ipcRenderer.invoke('recording:record-track', track, options),
    stopRecording: () => ipcRenderer.invoke('recording:stop'),
    playTrack: track => ipcRenderer.send('visualizer:play-track', track),
    togglePlayback: () => ipcRenderer.send('visualizer:toggle-playback'),
    stop: () => ipcRenderer.send('visualizer:stop'),
    next: () => ipcRenderer.send('visualizer:next'),
    previous: () => ipcRenderer.send('visualizer:previous'),
    trackEnded: () => ipcRenderer.send('visualizer:track-ended'),
    playbackState: state => ipcRenderer.send('visualizer:playback-state', state),
    seek: time => ipcRenderer.send('visualizer:seek', time),
    onPlayTrack: callback => ipcRenderer.on('visualizer:play-track', (_event, track) => callback(track)),
    onTogglePlayback: callback => ipcRenderer.on('visualizer:toggle-playback', callback),
    onStop: callback => ipcRenderer.on('visualizer:stop', callback),
    onNext: callback => ipcRenderer.on('library:next', callback),
    onPrevious: callback => ipcRenderer.on('library:previous', callback),
    onPlaybackState: callback => ipcRenderer.on('library:playback-state', (_event, state) => callback(state)),
    onRecordingStatus: callback => ipcRenderer.on('recording:status', (_event, state) => callback(state)),
    onSeek: callback => ipcRenderer.on('visualizer:seek', (_event, time) => callback(time)),
    showSongContextMenu: index => ipcRenderer.send('library:show-song-context-menu', index),
    onContextMenuCommand: callback => ipcRenderer.on('library:context-menu-command', (_event, command, index) => callback(command, index)),
    updateVisibility: visibility => ipcRenderer.send('library:update-visibility', visibility),
    getVisibilitySettings: () => ipcRenderer.invoke('visualizer:get-visibility'),
    onUpdateVisibility: callback => ipcRenderer.on('visualizer:update-visibility', (_event, visibility) => callback(visibility)),
});
